### ISSUE TITLE
When trying to add a list member into a segment I noticed the API searches by only the first letter in the email provided

### ISSUE THREAD

**Issue by ayyobro** [mailchimp/mcapi2-php-examples#9]
Take the following response: 

```
array:3 [
  "success_count" => 0
  "error_count" => 1
  "errors" => array:1 [
    0 => array:3 [
      "email" => "test@mail.com"
      "code" => 232
      "error" => "There is no record of the email address "t" in your account"
    ]
  ]
]
```

Notice that in the error string it says it search using only the letter "t" ( I used a real email on my local, but I replaced it here so you wouldn't know it ). I pass through the parameters correctly in the method:

```php
$member = $this->mailchimp->lists->staticSegmentMembersAdd($listID, $segmentID, [
    'email' => $email
]);

```

The listID, segmentID, and $email values are all correct and being added in the correct format, but I still keep getting the response. 

I should note that the email in question is actually in Mailchimp already as a subscriber, just trying to add it to a static segment. 

What am I doing wrong?

**Comment by toomuchpete** [comment]
Hi @ayyobro -- we can't use issues on this repository as a substitute for our support team, unfortunately! I'd encourage you to reach out to apihelp@mailchimp.com; they can get you squared away!

**Comment by ayyobro** [comment]
I actually went and used a different wrapper because 2.0 isn't going to be supported by Mailchimp anymore anyways, but thank you for the email because I already found a bug with their new API that they will need to be aware of. 

Cheers
